PRAGMA foreign_keys = ON;

CREATE TABLE DISTRICTS (
            CODE INTEGER PRIMARY KEY,
            NAME TEXT,
            REGION TEXT
        );
        CREATE TABLE MUNICIPALITIES (
            CODE INTEGER PRIMARY KEY,
            NAME TEXT,
            DISTRICT_CODE INTEGER,
            FOREIGN KEY(DISTRICT_CODE) REFERENCES DISTRICTS(CODE)
        );
        CREATE TABLE PARTIES (
            ACRONYM TEXT PRIMARY KEY,
            NAME TEXT
        );
        CREATE TABLE VOTINGS (
            MUNICIPALITY_CODE INTEGER,
            PARTY_ACRONYM TEXT,
            DETAILED_NAME TEXT,
            VOTES INTEGER,
            MANDATES INTEGER DEFAULT 0,
            TOTAL_VOTERS INTEGER,
            BLANK_VOTES INTEGER,
            NULL_VOTES INTEGER,
            PRIMARY KEY (MUNICIPALITY_CODE, PARTY_ACRONYM),
            FOREIGN KEY(MUNICIPALITY_CODE) REFERENCES MUNICIPALITIES(CODE),
            FOREIGN KEY(PARTY_ACRONYM) REFERENCES PARTIES(ACRONYM)
        );